[features]
seeds = false
skip-lint = false

[programs.devnet]
sold_issuance = "4nRcwXvRUmpQMfjza6tsYyp3h6UA9hpT47yuXUwdmizo"
sold_staking = "6GUDMDrbzne1qxpFF5WzeehZpC3gfAAoJ7GcHu7VNqjy"

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.15"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keys/test-kp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
