[features]
seeds = false
skip-lint = false

[programs.devnet]
sold_issuance = "E52KjA58odp3taqmaCuBFdDya3s4TA1ho4tSXoW2igxb"
sold_staking = "B6rAjGxw89UQCho4fLBGcEne9jadXv2QewPgpQ1SmUnw"

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.15"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keys/test-kp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
