[features]
seeds = false
skip-lint = false

[programs.localnet]
sold_issuance = "3ja6s1Pb55nhzhwYp4GY77n972iEQtWX55xoRwP2asCT"
sold_staking = "F9pkhuLyu1usfS5p6RCuXxeS2TQsAVqANo1M2iC8ze1t"

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.34"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kulture/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
