[features]
seeds = false
skip-lint = false
[programs.devnet]
pt-staking = "1pPDoX5yEfag7pUNGYmTss9AydSs2qpvRc75Ff6XFH2"
sold_issuance = "2EWh1kTyMUgv46FdwJYJP61LXvrhLp5CqDfy5gDoqggf"
sold_staking = "9fQsEayPeUdypEAjyE6HGBkPWqrkMnnJG8Sh5NBXwwAM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./keys/test-kp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
