[features]
seeds = false
skip-lint = false

[programs.localnet]
sold_issuance = "JCLA8ET4DCCsJsvNcaNBhpY8ZudFfAbpgspPBnni1NQy"
sold_staking = "EuhcfekB1smmCcNqr38FvXtmWGkDy3rx8u9L1hf7ee3E"

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.34"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./keys/test-kp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
