[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.15"

[features]
seeds = false
skip-lint = false
[programs.devnet]
pt-staking = "AdXJ8Sr46ujd9DSLP5LRyF1BrqxT9azqmQqN2oTyV8cz"
parity-issuance = "ALukFrRp8cFkWCEZamFVsBiFtxKYPLUUGRxskFh1g5ZX"
parity-staking = "BZzrzzNm14rcF8edGVYY2NHyj9aQURFXubgEdRJoyzvH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./keys/test-kp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
