[features]
seeds = false
skip-lint = false

[programs.localnet]
sold_issuance = "Ev4vixMJX6Czywj7TSjnmBapdoYmZkpVwU3cpT2akgYG"
sold_staking = "9PEGJqYZCKBWvX6X652MCKJkT7WthKYo3ypYqyVV8dJ5"

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.34"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./keys/test-kp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
